CREATE TABLE AUDIT_DATA 
(ID NUMBER, 
SOURCE_ID VARCHAR2(15 BYTE), 
SOURCE_SCHEMA_NAME VARCHAR2(30 BYTE), 
SOURCE_TABLE_NAME VARCHAR2(30 BYTE), 
SOURCE_COLUMN_NAME VARCHAR2(30 BYTE), 
SOURCE_VALUE_CONTEXT VARCHAR2(255 BYTE), 
OLD_VALUE VARCHAR2(4000 BYTE), 
NEW_VALUE VARCHAR2(4000 BYTE), 
OPERATION_TYPE VARCHAR2(10 BYTE), 
OPERATION_TIME TIMESTAMP (6), 
INITIATOR_IP VARCHAR2(15 BYTE), 
INITIATOR_LOGIN VARCHAR2(255 BYTE), 
SESSIONID NUMBER, 
TRANSACTION_ID NUMBER
);

COMMENT ON COLUMN AUDIT_DATA.SOURCE_ID IS 'ATRYBUT ENCJI =  * OPIS = Unikalny identyfikator rekordu audytowanej tabeli ';
COMMENT ON COLUMN AUDIT_DATA.SOURCE_SCHEMA_NAME IS 'ATRYBUT ENCJI =  * OPIS = Nazwa schematu z ktorego pochodzi audytowana tabela ';
COMMENT ON COLUMN AUDIT_DATA.SOURCE_TABLE_NAME IS 'ATRYBUT ENCJI =  * OPIS = Nazwa audytowanej tabeli ';
COMMENT ON COLUMN AUDIT_DATA.SOURCE_COLUMN_NAME IS 'ATRYBUT ENCJI =  * OPIS = Nazwa audytowanej kolumny ';
COMMENT ON COLUMN AUDIT_DATA.SOURCE_VALUE_CONTEXT IS 'ATRYBUT ENCJI =  * OPIS = Dodatkowa informacja opisujaca kontekst uzycia danej kolumny (np. dla referencji do slownikow znaczenie danej kolumny) ';
COMMENT ON COLUMN AUDIT_DATA.OLD_VALUE IS 'ATRYBUT ENCJI =  * OPIS = Wartosc kolumny przed zmiana (konwersja do VARCHAR) - przy INSERT = NULL ';
COMMENT ON COLUMN AUDIT_DATA.NEW_VALUE IS 'ATRYBUT ENCJI =  * OPIS = Wartosc kolumny po zmianie (konwersja do VARCHAR) - przy DELETE = NULL ';
COMMENT ON COLUMN AUDIT_DATA.OPERATION_TYPE IS 'ATRYBUT ENCJI =  * OPIS = Typ operacji: INSERT, UPDATE, DELETE ';
COMMENT ON COLUMN AUDIT_DATA.OPERATION_TIME IS 'ATRYBUT ENCJI =  * OPIS = Dokladny czas dokonania zmiany ';
COMMENT ON COLUMN AUDIT_DATA.INITIATOR_IP IS 'ATRYBUT ENCJI =  * OPIS = Adres IP stacji roboczej z ktroej dokonano zmiany ';
COMMENT ON COLUMN AUDIT_DATA.INITIATOR_LOGIN IS 'ATRYBUT ENCJI =  * OPIS = Login osoby, ktora dokonala zmiany ';
COMMENT ON TABLE AUDIT_DATA  IS 'ENCJA = Tabela audytowa * ALIAS = AUDA';
CREATE UNIQUE INDEX AUDA_PK ON AUDIT_DATA (ID);
CREATE INDEX AUDIT_DATA_I ON AUDIT_DATA (SOURCE_ID);
CREATE INDEX AUDIT_DATA_I2 ON AUDIT_DATA (SOURCE_COLUMN_NAME) ;

ALTER TABLE AUDIT_DATA ADD CONSTRAINT AUDA_PK PRIMARY KEY (ID)
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE LFPROD_TBLSPACE  ENABLE;
ALTER TABLE AUDIT_DATA MODIFY (OPERATION_TIME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA MODIFY (OPERATION_TYPE NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA MODIFY (SOURCE_COLUMN_NAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA MODIFY (SOURCE_TABLE_NAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA MODIFY (SOURCE_SCHEMA_NAME NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA MODIFY (SOURCE_ID NOT NULL ENABLE);
ALTER TABLE AUDIT_DATA MODIFY (ID NOT NULL ENABLE);

create sequence audit_transaction_id_s;
create sequence custom_main_seq;
